python -m sglang.launch_server \
    --model-path ../../../autodl-tmp/Mistral/ \
    --port 30000 \
    --disable-cuda-graph \
    --mem-fraction-static 0.8 \
    --disable-radix-cache \
    --disable-context-len-check \
    --page-size 1 \
    --chunked-prefill-size -1 \
    --max-prefill-tokens 120000 \
    --attention-backend compressed_fa3 \
    --kv-compression-ratio 0.5